// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { chatsCreate, chatsDelete, chatsGet, chatsList, chatsUpdate, documentsDelete, documentsDownload, documentsList, documentsUpload, healthCheck, messagesCreate, messagesList, type Options } from '../sdk.gen';
import type { ChatsCreateData, ChatsCreateError, ChatsCreateResponse, ChatsDeleteData, ChatsDeleteError, ChatsDeleteResponse, ChatsGetData, ChatsGetError, ChatsGetResponse, ChatsListData, ChatsListResponse, ChatsUpdateData, ChatsUpdateError, ChatsUpdateResponse, DocumentsDeleteData, DocumentsDeleteError, DocumentsDeleteResponse, DocumentsDownloadData, DocumentsDownloadError, DocumentsListData, DocumentsListError, DocumentsListResponse, DocumentsUploadData, DocumentsUploadError, DocumentsUploadResponse, HealthCheckData, HealthCheckResponse, MessagesCreateData, MessagesCreateError, MessagesCreateResponse, MessagesListData, MessagesListError, MessagesListResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const chatsListQueryKey = (options?: Options<ChatsListData>) => createQueryKey('chatsList', options);

/**
 * List
 */
export const chatsListOptions = (options?: Options<ChatsListData>) => queryOptions<ChatsListResponse, DefaultError, ChatsListResponse, ReturnType<typeof chatsListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await chatsList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatsListQueryKey(options)
});

/**
 * Create
 */
export const chatsCreateMutation = (options?: Partial<Options<ChatsCreateData>>): UseMutationOptions<ChatsCreateResponse, ChatsCreateError, Options<ChatsCreateData>> => {
    const mutationOptions: UseMutationOptions<ChatsCreateResponse, ChatsCreateError, Options<ChatsCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await chatsCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete
 */
export const chatsDeleteMutation = (options?: Partial<Options<ChatsDeleteData>>): UseMutationOptions<ChatsDeleteResponse, ChatsDeleteError, Options<ChatsDeleteData>> => {
    const mutationOptions: UseMutationOptions<ChatsDeleteResponse, ChatsDeleteError, Options<ChatsDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await chatsDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const chatsGetQueryKey = (options: Options<ChatsGetData>) => createQueryKey('chatsGet', options);

/**
 * Get
 */
export const chatsGetOptions = (options: Options<ChatsGetData>) => queryOptions<ChatsGetResponse, ChatsGetError, ChatsGetResponse, ReturnType<typeof chatsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await chatsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatsGetQueryKey(options)
});

/**
 * Update
 */
export const chatsUpdateMutation = (options?: Partial<Options<ChatsUpdateData>>): UseMutationOptions<ChatsUpdateResponse, ChatsUpdateError, Options<ChatsUpdateData>> => {
    const mutationOptions: UseMutationOptions<ChatsUpdateResponse, ChatsUpdateError, Options<ChatsUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await chatsUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const documentsListQueryKey = (options: Options<DocumentsListData>) => createQueryKey('documentsList', options);

/**
 * List
 */
export const documentsListOptions = (options: Options<DocumentsListData>) => queryOptions<DocumentsListResponse, DocumentsListError, DocumentsListResponse, ReturnType<typeof documentsListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await documentsList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: documentsListQueryKey(options)
});

/**
 * Upload
 */
export const documentsUploadMutation = (options?: Partial<Options<DocumentsUploadData>>): UseMutationOptions<DocumentsUploadResponse, DocumentsUploadError, Options<DocumentsUploadData>> => {
    const mutationOptions: UseMutationOptions<DocumentsUploadResponse, DocumentsUploadError, Options<DocumentsUploadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await documentsUpload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const documentsDownloadQueryKey = (options: Options<DocumentsDownloadData>) => createQueryKey('documentsDownload', options);

/**
 * Download
 */
export const documentsDownloadOptions = (options: Options<DocumentsDownloadData>) => queryOptions<unknown, DocumentsDownloadError, unknown, ReturnType<typeof documentsDownloadQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await documentsDownload({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: documentsDownloadQueryKey(options)
});

/**
 * Delete
 */
export const documentsDeleteMutation = (options?: Partial<Options<DocumentsDeleteData>>): UseMutationOptions<DocumentsDeleteResponse, DocumentsDeleteError, Options<DocumentsDeleteData>> => {
    const mutationOptions: UseMutationOptions<DocumentsDeleteResponse, DocumentsDeleteError, Options<DocumentsDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await documentsDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const messagesListQueryKey = (options: Options<MessagesListData>) => createQueryKey('messagesList', options);

/**
 * List
 */
export const messagesListOptions = (options: Options<MessagesListData>) => queryOptions<MessagesListResponse, MessagesListError, MessagesListResponse, ReturnType<typeof messagesListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await messagesList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: messagesListQueryKey(options)
});

/**
 * Create
 */
export const messagesCreateMutation = (options?: Partial<Options<MessagesCreateData>>): UseMutationOptions<MessagesCreateResponse, MessagesCreateError, Options<MessagesCreateData>> => {
    const mutationOptions: UseMutationOptions<MessagesCreateResponse, MessagesCreateError, Options<MessagesCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await messagesCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) => createQueryKey('healthCheck', options);

/**
 * Check
 */
export const healthCheckOptions = (options?: Options<HealthCheckData>) => queryOptions<HealthCheckResponse, DefaultError, HealthCheckResponse, ReturnType<typeof healthCheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckQueryKey(options)
});
