// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChatsCreateData, ChatsCreateErrors, ChatsCreateResponses, ChatsDeleteData, ChatsDeleteErrors, ChatsDeleteResponses, ChatsGetData, ChatsGetErrors, ChatsGetResponses, ChatsListData, ChatsListResponses, ChatsUpdateData, ChatsUpdateErrors, ChatsUpdateResponses, DocumentsDeleteData, DocumentsDeleteErrors, DocumentsDeleteResponses, DocumentsDownloadData, DocumentsDownloadErrors, DocumentsDownloadResponses, DocumentsListData, DocumentsListErrors, DocumentsListResponses, DocumentsUploadData, DocumentsUploadErrors, DocumentsUploadResponses, HealthCheckData, HealthCheckResponses, MessagesCreateData, MessagesCreateErrors, MessagesCreateResponses, MessagesListData, MessagesListErrors, MessagesListResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List
 */
export const chatsList = <ThrowOnError extends boolean = false>(options?: Options<ChatsListData, ThrowOnError>): RequestResult<ChatsListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ChatsListResponses, unknown, ThrowOnError>({ url: '/chats', ...options });

/**
 * Create
 */
export const chatsCreate = <ThrowOnError extends boolean = false>(options?: Options<ChatsCreateData, ThrowOnError>): RequestResult<ChatsCreateResponses, ChatsCreateErrors, ThrowOnError> => (options?.client ?? client).post<ChatsCreateResponses, ChatsCreateErrors, ThrowOnError>({
    url: '/chats',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete
 */
export const chatsDelete = <ThrowOnError extends boolean = false>(options: Options<ChatsDeleteData, ThrowOnError>): RequestResult<ChatsDeleteResponses, ChatsDeleteErrors, ThrowOnError> => (options.client ?? client).delete<ChatsDeleteResponses, ChatsDeleteErrors, ThrowOnError>({ url: '/chats/{chat_id}', ...options });

/**
 * Get
 */
export const chatsGet = <ThrowOnError extends boolean = false>(options: Options<ChatsGetData, ThrowOnError>): RequestResult<ChatsGetResponses, ChatsGetErrors, ThrowOnError> => (options.client ?? client).get<ChatsGetResponses, ChatsGetErrors, ThrowOnError>({ url: '/chats/{chat_id}', ...options });

/**
 * Update
 */
export const chatsUpdate = <ThrowOnError extends boolean = false>(options: Options<ChatsUpdateData, ThrowOnError>): RequestResult<ChatsUpdateResponses, ChatsUpdateErrors, ThrowOnError> => (options.client ?? client).patch<ChatsUpdateResponses, ChatsUpdateErrors, ThrowOnError>({
    url: '/chats/{chat_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List
 */
export const documentsList = <ThrowOnError extends boolean = false>(options: Options<DocumentsListData, ThrowOnError>): RequestResult<DocumentsListResponses, DocumentsListErrors, ThrowOnError> => (options.client ?? client).get<DocumentsListResponses, DocumentsListErrors, ThrowOnError>({ url: '/chats/{chat_id}/documents', ...options });

/**
 * Upload
 */
export const documentsUpload = <ThrowOnError extends boolean = false>(options: Options<DocumentsUploadData, ThrowOnError>): RequestResult<DocumentsUploadResponses, DocumentsUploadErrors, ThrowOnError> => (options.client ?? client).post<DocumentsUploadResponses, DocumentsUploadErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/chats/{chat_id}/documents',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Download
 */
export const documentsDownload = <ThrowOnError extends boolean = false>(options: Options<DocumentsDownloadData, ThrowOnError>): RequestResult<DocumentsDownloadResponses, DocumentsDownloadErrors, ThrowOnError> => (options.client ?? client).get<DocumentsDownloadResponses, DocumentsDownloadErrors, ThrowOnError>({ url: '/documents/{document_id}/download', ...options });

/**
 * Delete
 */
export const documentsDelete = <ThrowOnError extends boolean = false>(options: Options<DocumentsDeleteData, ThrowOnError>): RequestResult<DocumentsDeleteResponses, DocumentsDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DocumentsDeleteResponses, DocumentsDeleteErrors, ThrowOnError>({ url: '/documents/{document_id}', ...options });

/**
 * List
 */
export const messagesList = <ThrowOnError extends boolean = false>(options: Options<MessagesListData, ThrowOnError>): RequestResult<MessagesListResponses, MessagesListErrors, ThrowOnError> => (options.client ?? client).get<MessagesListResponses, MessagesListErrors, ThrowOnError>({ url: '/chats/{chat_id}/messages', ...options });

/**
 * Create
 */
export const messagesCreate = <ThrowOnError extends boolean = false>(options: Options<MessagesCreateData, ThrowOnError>): RequestResult<MessagesCreateResponses, MessagesCreateErrors, ThrowOnError> => (options.client ?? client).post<MessagesCreateResponses, MessagesCreateErrors, ThrowOnError>({
    url: '/chats/{chat_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });
