// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_documents-upload
 */
export type BodyDocumentsUpload = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * ChatCreate
 */
export type ChatCreate = {
    /**
     * Title
     */
    title?: string | null;
};

/**
 * ChatOut
 */
export type ChatOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ChatUpdate
 */
export type ChatUpdate = {
    /**
     * Title
     */
    title: string;
};

/**
 * DocumentOut
 */
export type DocumentOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Chat Id
     */
    chat_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error: string | null;
    /**
     * Chunk Count
     */
    chunk_count: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * EvaluationQuestionOut
 */
export type EvaluationQuestionOut = {
    /**
     * Question
     */
    question: string;
    /**
     * Response
     */
    response: string;
    /**
     * Reference
     */
    reference: string;
    /**
     * Retrieved Contexts
     */
    retrieved_contexts?: string | Array<string> | null;
    /**
     * Scores
     */
    scores?: {
        [key: string]: number;
    };
};

/**
 * EvaluationRunOut
 */
export type EvaluationRunOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    summary: EvaluationSummaryOut;
    /**
     * Questions
     */
    questions: Array<EvaluationQuestionOut>;
};

/**
 * EvaluationRunSummaryOut
 */
export type EvaluationRunSummaryOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    summary: EvaluationSummaryOut;
};

/**
 * EvaluationSummaryOut
 */
export type EvaluationSummaryOut = {
    /**
     * Question Count
     */
    question_count: number;
    /**
     * Scored Count
     */
    scored_count: number;
    /**
     * Overall Score
     */
    overall_score?: number | null;
    /**
     * Metrics
     */
    metrics: {
        [key: string]: MetricStatsOut;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageCreate
 */
export type MessageCreate = {
    /**
     * Content
     */
    content: string;
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Chat Id
     */
    chat_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Sources
     */
    sources?: Array<SourceOut> | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MetricStatsOut
 */
export type MetricStatsOut = {
    /**
     * Label
     */
    label: string;
    /**
     * Mean
     */
    mean: number;
    /**
     * Min
     */
    min: number;
    /**
     * Max
     */
    max: number;
};

/**
 * SourceOut
 */
export type SourceOut = {
    /**
     * Document Id
     */
    document_id?: string | null;
    /**
     * Filename
     */
    filename?: string | null;
    /**
     * Page
     */
    page?: number | null;
    /**
     * Text
     */
    text: string;
    /**
     * Score
     */
    score?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chats';
};

export type ChatsListResponses = {
    /**
     * Response Chats-List
     *
     * Successful Response
     */
    200: Array<ChatOut>;
};

export type ChatsListResponse = ChatsListResponses[keyof ChatsListResponses];

export type ChatsCreateData = {
    /**
     * Body
     */
    body?: ChatCreate | null;
    path?: never;
    query?: never;
    url: '/chats';
};

export type ChatsCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatsCreateError = ChatsCreateErrors[keyof ChatsCreateErrors];

export type ChatsCreateResponses = {
    /**
     * Successful Response
     */
    201: ChatOut;
};

export type ChatsCreateResponse = ChatsCreateResponses[keyof ChatsCreateResponses];

export type ChatsDeleteData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type ChatsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatsDeleteError = ChatsDeleteErrors[keyof ChatsDeleteErrors];

export type ChatsDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChatsDeleteResponse = ChatsDeleteResponses[keyof ChatsDeleteResponses];

export type ChatsGetData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type ChatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatsGetError = ChatsGetErrors[keyof ChatsGetErrors];

export type ChatsGetResponses = {
    /**
     * Successful Response
     */
    200: ChatOut;
};

export type ChatsGetResponse = ChatsGetResponses[keyof ChatsGetResponses];

export type ChatsUpdateData = {
    body: ChatUpdate;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type ChatsUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatsUpdateError = ChatsUpdateErrors[keyof ChatsUpdateErrors];

export type ChatsUpdateResponses = {
    /**
     * Successful Response
     */
    200: ChatOut;
};

export type ChatsUpdateResponse = ChatsUpdateResponses[keyof ChatsUpdateResponses];

export type DocumentsListData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}/documents';
};

export type DocumentsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsListError = DocumentsListErrors[keyof DocumentsListErrors];

export type DocumentsListResponses = {
    /**
     * Response Documents-List
     *
     * Successful Response
     */
    200: Array<DocumentOut>;
};

export type DocumentsListResponse = DocumentsListResponses[keyof DocumentsListResponses];

export type DocumentsUploadData = {
    body: BodyDocumentsUpload;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}/documents';
};

export type DocumentsUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsUploadError = DocumentsUploadErrors[keyof DocumentsUploadErrors];

export type DocumentsUploadResponses = {
    /**
     * Response Documents-Upload
     *
     * Successful Response
     */
    202: Array<DocumentOut>;
};

export type DocumentsUploadResponse = DocumentsUploadResponses[keyof DocumentsUploadResponses];

export type DocumentsDownloadData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/download';
};

export type DocumentsDownloadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDownloadError = DocumentsDownloadErrors[keyof DocumentsDownloadErrors];

export type DocumentsDownloadResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsDeleteData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}';
};

export type DocumentsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDeleteError = DocumentsDeleteErrors[keyof DocumentsDeleteErrors];

export type DocumentsDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DocumentsDeleteResponse = DocumentsDeleteResponses[keyof DocumentsDeleteResponses];

export type MessagesListData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}/messages';
};

export type MessagesListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessagesListError = MessagesListErrors[keyof MessagesListErrors];

export type MessagesListResponses = {
    /**
     * Response Messages-List
     *
     * Successful Response
     */
    200: Array<MessageOut>;
};

export type MessagesListResponse = MessagesListResponses[keyof MessagesListResponses];

export type MessagesCreateData = {
    body: MessageCreate;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}/messages';
};

export type MessagesCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessagesCreateError = MessagesCreateErrors[keyof MessagesCreateErrors];

export type MessagesCreateResponses = {
    /**
     * Successful Response
     */
    200: MessageOut;
};

export type MessagesCreateResponse = MessagesCreateResponses[keyof MessagesCreateResponses];

export type EvaluationLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/evaluation';
};

export type EvaluationLatestResponses = {
    /**
     * Successful Response
     */
    200: EvaluationRunOut;
};

export type EvaluationLatestResponse = EvaluationLatestResponses[keyof EvaluationLatestResponses];

export type EvaluationListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/evaluation/runs';
};

export type EvaluationListResponses = {
    /**
     * Response Evaluation-List
     *
     * Successful Response
     */
    200: Array<EvaluationRunSummaryOut>;
};

export type EvaluationListResponse = EvaluationListResponses[keyof EvaluationListResponses];

export type EvaluationGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/evaluation/runs/{run_id}';
};

export type EvaluationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EvaluationGetError = EvaluationGetErrors[keyof EvaluationGetErrors];

export type EvaluationGetResponses = {
    /**
     * Successful Response
     */
    200: EvaluationRunOut;
};

export type EvaluationGetResponse = EvaluationGetResponses[keyof EvaluationGetResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthCheckResponses = {
    /**
     * Response Health-Check
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
